### ISSUE TITLE
Loading of libssl.so and libcrypto.so fails

### ISSUE THREAD

**Issue by Ifilehk** [JKRhb/dtls2#44]
Hello there,

First of all thank you for your nice contribution !!!

Was struggling with importing the libraries for and android project in Android Studio but managed to get it work after modifying your code. Strangely your code works for a dart Linux application without modification. Maybe you have an idea why.

For android I had to swap lines in dtls_client.dart this way.
  DtlsClient(
    this._socket, {
    DynamicLibrary? libCrypto,   <--- swapped with next
    DynamicLibrary? libSsl,   <--- swapped
  })  : _libCrypto = _loadOpenSsl(libCrypto) ?? lib.libCrypto,   <--- swapped with next
        _libSsl = _loadOpenSsl(libSsl) ?? lib.libSsl {   <--- swapped
    _startListening();
  }

**Comment by JKRhb** [comment]
Closing this one as completed for the time being, if you experience any more issues feel free to reopen it :)
