### ISSUE TITLE
Catch the unhandled Exception Network is unreachable

### ISSUE THREAD

**Issue by Ifilehk** [JKRhb/dtls2#54]
This exception occurs when during an open connection the adapter is turned off. Not really annoying on Desktops but on mobiles where we often turn WIFI on and off a must. I realized that this exception cannot be catch for what ever isolates reasons but a check of number of returned written bytes from `_socket.send` can help.

>Unhandled exception:
SocketException: Send failed (OS Error: Network is unreachable, errno = 101), address = ::, port = 8888
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1224:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2491:15)
#2      _DtlsServerConnection._maintainOutgoing (package:dtls2/src/dtls_server.dart:315:27)
#3      _DtlsServerConnection._maintainState (package:dtls2/src/dtls_server.dart:282:9)
#4      _DtlsServerConnection.close (package:dtls2/src/dtls_server.dart:350:7)
#5      Server.connect.<anonymous closure>.<anonymous closure> (package:ptt_server/server_socket.dart:333:24)
#6      ConnectionTimer.start.<anonymous closure> (package:ptt_server/server_socket.dart:268:16)
#7      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#8      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#9      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#10     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)

**Comment by JKRhb** [comment]
Thank you for pointing this out, @Ifilehk! Do you already have a potential patch ready that could be applied to address this issue?

**Comment by JKRhb** [comment]
Can you have a look at #55? After merging I will release a new patch version.
