### ISSUE TITLE
Since 0.13.3 client cannot connect to server with returned code 2 (SSL3_AL_FATAL)

### ISSUE THREAD

**Issue by Ifilehk** [JKRhb/dtls2#65]
This is related to the code 2 SS3_AL_FAILURE.
```
I/flutter (15946): void _connectToPeer() { --> before --> _handleError(ret, _connectCompleter.completeError);
I/flutter (15946): start --> void _handleError(int ret, void Function(Exception) errorHandler) {
I/flutter (15946): _handleError(int ret, void Function(Exception) errorHandler) { --> after --> final code = _libSsl.SSL_get_error(_ssl, ret); code=2
```

I realized that downgrading the server to 0.13.2 works.
So there is a bug on the server side in 0.13.3.

In both cases client was on 0.13.3. So client is fine (with my fix proposal)

**Comment by JKRhb** [comment]
Awesome! :) Just released version `0.13.4` with the fixes, let me know if you notice anything else :)

**Comment by Ifilehk** [comment]
I will update to 0.13.4 and let you know ...

**Comment by Ifilehk** [comment]
Hallo Jan. You can close this issue because fixed! Thank you for your support!
