### ISSUE TITLE
Network is unreachable treated as DTLSException ?

### ISSUE THREAD

**Issue by Ifilehk** [JKRhb/dtls2#71]
Back again :-)

Having trouble to catch `Network is unreachable` exception.

As I can see `_abortHandshake(DtlsException("Network is unreachable"));` it is treated as DtlsException and I am not managing to catch it.

Would it not be preferable to throw it as a SocketException like thrown by the underlying system?

**Comment by JKRhb** [comment]
Oh, sorry, that was a mistake from my side 😅 I opened #72 as a fix and will release a new version shortly :)

**Comment by JKRhb** [comment]
Just release version 0.14.1 with the fix, sorry for the inconvenience!

**Comment by Ifilehk** [comment]
No problem :-)
