### ISSUE TITLE
Fatal exception with no trace

### ISSUE THREAD

**Issue by Ifilehk** [JKRhb/dtls2#88]
Digging is always good :-)

Was trying to understand the handshake and manipulated using `openssl s_client. Crashed my usecase server and the minimal server used yesterday too. Unfortunately no trace is available. Note that that if the server runs on my linux machine, there is no crash. But on my cloud server one can see the following trace. So I suspect different libssl version.
ret = is a print inside  _maintainOutgoing() in dtls_server.dart

If you have an idea will let you go for it otherwise will try to narrow it down ...

Oh yes her the crash trigger: `openssl s_client -dtls -psk_identity "" -psk "" -connect XX.XX.XX.XX:PPPP`

```
Server listening on port 8888

ret = 60
ret = -1
New connection

===== CRASH =====
si_signo=Segmentation fault(11), si_code=1, si_addr=0x110
```

**Comment by JKRhb** [comment]
Thank you for reporting this issue! I actually found the bug: The crash occurs when you send a PSK with zero length (using a zero-length identity works, however). Will try to provide a fix ASAP.

**Comment by Ifilehk** [comment]
Cannot confirm.

`openssl s_client -dtls -psk_identity "ABCDE" -psk "AAAAAAAAAAAAAAAAAA" -connect XX.XX.XX.XX:PPPP`

does the same.

```
Server listening on port 8888

ret = 60
ret = -1
New connection

===== CRASH =====
si_signo=Segmentation fault(11), si_code=1, si_addr=0x110
```

**Comment by Ifilehk** [comment]
As as stated before same command `openssl s_client -dtls -psk_identity "ABCDE" -psk "AAAAAAAAAAAAAAAAAA" -connect localhost:8888`, on my local server no crash. Just on the cloud server.

```
Server listening on port 8888

ret = 60
ret = -1
New connection
ret = 60
ret = 60
ret = 60
```

**Comment by JKRhb** [comment]
Hmm, okay, then the empty PSK is actually a different bug :D 

Do you have any way of checking the OpenSSL version on the server?

**Comment by Ifilehk** [comment]
`strings /usr/lib/x86_64-linux-gnu/libssl.so | grep "^OpenSSL"`
`OpenSSL 1.1.1d  10 Sep 2019`

**Comment by Ifilehk** [comment]
on my local machine
```
Package: libssl3                  
Version: 3.0.8-1ubuntu1.2
```

**Comment by Ifilehk** [comment]
What is making the server crash is when PSK is not multiple of 8bits.
No crash: `openssl s_client -dtls -psk_identity "R" -psk "1A" -cipher "PSK-AES128-CCM8" -connect <IP>:<PORT>` 
Crash: `openssl s_client -dtls -psk_identity "R" -psk "1AB" -cipher "PSK-AES128-CCM8" -connect <IP>:<PORT>`

**Comment by Ifilehk** [comment]
> Thank you for reporting this issue! I actually found the bug: The crash occurs when you send a PSK with zero length (using a zero-length identity works, however). Will try to provide a fix ASAP.

Please consider the client side too. Client crashing on empty PSK string too.

```
Unhandled exception:
SocketException: Send failed (OS Error: Message too long, errno = 90), address = 0.0.0.0, port = 0
#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1246:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2516:15)
#2      _DtlsClientConnection._maintainOutgoing (package:dtls2/src/dtls_client.dart:565:31)
#3      _DtlsClientConnection._connectToPeer (package:dtls2/src/dtls_client.dart:498:21)
#4      _DtlsClientConnection._maintainState (package:dtls2/src/dtls_client.dart:596:7)
#5      _DtlsClientConnection._incoming (package:dtls2/src/dtls_client.dart:557:5)
#6      DtlsClient._startListening.<anonymous closure> (package:dtls2/src/dtls_client.dart:87:26)
#7      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
```

**Comment by JKRhb** [comment]
Hmm, with the current state on the main branch, I cannot reproduce the errors anymore using OpenSSL 3. Can you try upgrading and testing again?

**Comment by Ifilehk** [comment]
OK. Results with main branch on my cloud server on `OpenSSL 1.1.1d  10 Sep 2019`:
No crash: openssl s_client -dtls -psk_identity "R" -psk "1A" -cipher "PSK-AES128-CCM8" -connect <IP>:<PORT>
Crash: openssl s_client -dtls -psk_identity "R" -psk "01A" -cipher "PSK-AES128-CCM8" -connect <IP>:<PORT>

With an uneven number of bytes in the parameter psk I can still observe the crash.

**Comment by Ifilehk** [comment]
Hello. No problem for the delay.

The issue is related to the number of bytes of the PSK. It has to be even to avoid the crash. At the moment, I don't have enough insight of your code to tell you where to patch. But the fact is. Uneven number of bytes triggers a crash as stated above.

Example to reproduce is simple. Use the minimal server and try to connect to it using the command:

openssl s_client -dtls -psk_identity "R" -psk "01A" -cipher "PSK-AES128-CCM8" -connect IP:PORT

Let me know if you succeed to reproduce me it.

**Comment by Ifilehk** [comment]
Morgen!

In fact on libssl3 and this is I suppose what you have on your local machine, there is no crash as stated here https://github.com/JKRhb/dtls2/issues/88#issuecomment-1632513769.

Crash is seen on my cloud server running on libssl1. So as you said it is obviously a libssl1 problem, but dtls2 has to catch this before it happens, otherwise all the app crashes.

Wouldn't be possible to dtlstimeout when the PSK is null or uneven in number of bytes ?

**Comment by Ifilehk** [comment]
Any news at this front ?

**Comment by JKRhb** [comment]
Hi @Ifilehk, sorry, I only found the time to deal with the issue again now. If you are active working in this area, please have a look at #97 as a potential fix for the problem.

I tested it locally against OpenSSL version 1.1.1d and the inputs provided by you above and the server was able to handle the incorrectly formatted inputs now. The tests are, for some reason, currently failing on Windows, but I hope to be able to resolve these problems shortly. On Linux, you should already be able to perform tests with the updates on that branch.
