### ISSUE TITLE
DtlsException("Sending failed: Not connected!").  Is this exception correctly labeled ?

### ISSUE THREAD

**Issue by Ifilehk** [JKRhb/dtls2#91]
I was thinking if this exception is correctly labeled.

Actually the connection is closed so we are no more in a dtls context so asking my self if it belongs there.

The openssl s_client behaves returning `read:errno=111`. Same error is thrown when trying to connect on a server that is down.
https://github.com/openssl/openssl/blob/1e398bec538978b9957e69bf9e12b3c626290bea/apps/s_client.c#L3207-L3213

what is a socket error.

https://github.com/JKRhb/dtls2/blob/bb19bdfb6daf5d4643799b5451ed7f143b63a4ee/lib/src/dtls_client.dart#L521-L529

**Comment by JKRhb** [comment]
Hmm, so instead of `DtlsException` a `SocketExcption` should be thrown here, right?

**Comment by Ifilehk** [comment]
I think so.
